### ISSUE TITLE
Review Data Model, suggest filter

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/data_model#13]
```User Story:   As an ACED-Researcher, in order to donate data,  I need a concise, achievable target - a list of entities and properties to populate.```

The current data model accurately renders `all` the entities in the synthetic population model. 

Some of them, perhaps [Claim, Device, ...],  should be filtered out.

Review the models in `/doc/*.png` and suggest filters.

**Comment by bwalsh** [comment]
For discussion: core entities?

![image](https://user-images.githubusercontent.com/47808/191331166-e524f9db-c659-4cc5-8a0b-82493c84e6c8.png)

@lbeckman314 @jordan2lee

**Comment by bwalsh** [comment]
Possible additional entities
![image](https://user-images.githubusercontent.com/47808/191330760-6e7d7bc6-5ad0-4307-acd5-36374780c364.png)

**Comment by bwalsh** [comment]
@lbeckman314

**Comment by jordan2lee** [comment]
@bwalsh Yellow fields are your suggestions for core entities? or all shown?

**Comment by jordan2lee** [comment]
Looks like you've pinpointed most of the core entities. I would add to core: imaging study, encounter (appears to be like a dr visit, the time stamps might be useful in avoiding dups), and procedure (useful for patient derived samples).

Tempted to suggest adding condition too, though I don't have a good grasp of what examples of this would be. Condition could be a good "catch all" entity. What do you two think?

Could remove task from core. we would still be able to link patients to docs without this. might be more of a field for nurse/docs to inform next steps for patients

**Comment by jordan2lee** [comment]
Also what do you two think of Media and Device? Some examples in the data are electrocardiogram and implantable defibrillator (respectively). I feel we could go without and if these fields are relevant to a study, then could throw these in a "catch all remaining" entity

**Comment by bwalsh** [comment]
agree re. condition, procedure, encounter and imaging_study
also agree not including media and device
